# Generated by Django 5.1.5 on 2025-06-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pret_redus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagine_principala', models.ImageField(upload_to='produse/')),
                ('categorie', models.CharField(max_length=100)),
                ('in_stoc', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('numar_reviewuri', models.IntegerField(default=0)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('descriere_detaliata', models.TextField(blank=True, help_text='Descriere completă a produsului', null=True)),
                ('specificatii', models.TextField(blank=True, help_text='Specificații tehnice (JSON sau text simplu)', null=True)),
                ('dimensiuni', models.CharField(blank=True, max_length=100, null=True)),
                ('greutate', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('tara_origine', models.CharField(blank=True, max_length=100, null=True)),
                ('garantie', models.CharField(blank=True, max_length=100, null=True)),
                ('instructiuni_utilizare', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, unique=True)),
                ('capitala', models.CharField(max_length=100)),
                ('populatie', models.PositiveIntegerField()),
                ('suprafata', models.PositiveIntegerField()),
                ('inaltime_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('inaltime_minima', models.IntegerField(blank=True, null=True)),
                ('cel_mai_mare_oras', models.CharField(blank=True, max_length=100, null=True)),
                ('moneda', models.CharField(max_length=50)),
                ('limba', models.CharField(max_length=50)),
                ('sistem_politic', models.CharField(max_length=100)),
                ('conducator', models.CharField(blank=True, max_length=100, null=True)),
                ('imagine_principala', models.ImageField(blank=True, null=True, upload_to='imagini_tari/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='imagini_tari/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='imagini_tari/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='imagini_tari/')),
            ],
        ),
        migrations.CreateModel(
            name='ImaginiProdus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagine', models.ImageField(upload_to='produse/imagini/')),
                ('titlu', models.CharField(blank=True, max_length=200, null=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagini', to='tarile.produs')),
            ],
            options={
                'verbose_name': 'Imagine Produs',
                'verbose_name_plural': 'Imagini Produse',
                'ordering': ['ordine'],
            },
        ),
    ]
