# Generated by Django 5.1.5 on 2025-06-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pret_redus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagine_principala', models.ImageField(upload_to='produse/')),
                ('categorie', models.CharField(max_length=100)),
                ('in_stoc', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('numar_reviewuri', models.IntegerField(default=0)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
