# Generated by Django 5.1.5 on 2025-06-04 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarile', '0002_produs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodReducere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, unique=True)),
                ('tip', models.CharField(choices=[('procent', 'Procent'), ('suma', 'Sumă fixă'), ('livrare', 'Livrare gratuită')], max_length=10)),
                ('valoare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activ', models.BooleanField(default=True)),
                ('data_expirare', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurareTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timp_livrare', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='produs',
            name='descriere_detaliata',
            field=models.TextField(blank=True, help_text='Descriere completă a produsului', null=True),
        ),
        migrations.AddField(
            model_name='produs',
            name='dimensiuni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produs',
            name='garantie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produs',
            name='greutate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produs',
            name='instructiuni_utilizare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produs',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produs',
            name='specificatii',
            field=models.TextField(blank=True, help_text='Specificații tehnice (JSON sau text simplu)', null=True),
        ),
        migrations.AddField(
            model_name='produs',
            name='tara_origine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_comanda', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('in_asteptare', 'În așteptare'), ('procesata', 'Procesată'), ('livrata', 'Livrată'), ('anulata', 'Anulată')], default='in_asteptare', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_comanda', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComandaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tarile.comanda')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarile.produs')),
            ],
        ),
        migrations.CreateModel(
            name='Cos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CosItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1)),
                ('cos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tarile.cos')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarile.produs')),
            ],
        ),
    ]
