# Generated by Django 5.1.5 on 2025-06-04 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarile', '0003_codreducere_configuraretransport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='adresa',
            field=models.CharField(default='Adresa nedefinita', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='cod_postal',
            field=models.CharField(default='00000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='cost_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='data_livrare_estimata',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='email',
            field=models.EmailField(default='email@nedefinit.ro', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='judet',
            field=models.CharField(default='judet nedefinit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='metoda_plata',
            field=models.CharField(default='card', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='nume_complet',
            field=models.CharField(default='Nume nedefinit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='observatii_livrare',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='oras',
            field=models.CharField(default='oras nedefinit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='telefon',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cos',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('in_asteptare', 'În așteptare'), ('confirmed', 'Confirmată'), ('procesata', 'Procesată'), ('livrata', 'Livrată'), ('anulata', 'Anulată')], default='in_asteptare', max_length=20),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cos',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
