# Generated by Django 5.1.5 on 2025-06-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarile', '0004_comanda_adresa_comanda_cod_postal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comandaitem',
            old_name='pret',
            new_name='pret_unitar',
        ),
        migrations.AddField(
            model_name='comandaitem',
            name='nume_produs',
            field=models.CharField(default='nume', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comandaitem',
            name='total_pret',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuraretransport',
            name='zile_livrare_standard',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='adresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='cod_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='cost_transport',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='judet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='metoda_plata',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='numar_comanda',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='nume_complet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='observatii_livrare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='oras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comandaitem',
            name='produs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarile.produs'),
        ),
    ]
